# Config Client
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}

# Fallback (local defaults)
spring.application.name=ReviewReportService
server.port=8084

logging.level.org.springframework.cloud.config.client=DEBUG
