spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}

spring.application.name=ForumService
server.port=8006

logging.level.org.springframework.cloud.config.client=DEBUG
