spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true

spring.application.name=DIETSERVICE
server.port=8008

logging.level.org.springframework.cloud.config.client=DEBUG