server.port=3000
spring.data.mongodb.uri=mongodb://delivery-db:27017/delivery_db
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=delivery-service
eureka.instance.instanceId=delivery-service:${server.port}
